### ISSUE TITLE
Fails on activation keys "'localhost' is undefined"

### ISSUE THREAD

**Issue by smossber** [ture-karlsson/sat6-deployer#5]
Run goes fine up until the activation key task.

Running the playbook from the Satellite host itself. 
```
# hosts
[satellite]
satellite.example.com
```
```
# ansible-playbook sat6-configure.yml -v
```

```
TASK [sat6-content-views-publish-and-promote : publish a new version of each content view and promote it to all lifecycle environments] ******************************************************************************************************
changed: [satellite.example.com -> localhost] => (item={u'repositories': [{u'product': u'Red Hat Enterprise Linux Server', u'name': u'Red Hat Enterprise Linux 7 Server RPMs x86_64 7Server'}, {u'product': u'Red Hat Enterprise Linux Server', u'name': u'Red Hat Enterprise Linux 7 Server Kickstart x86_64 7.7'}, {u'product': u'Extra Packages For Enterprise Linux', u'name': u'EPEL-7'}], u'name': u'CV-RHEL7', u'filters': [{u'product': u'Extra Packages For Enterprise Linux', u'name': u'Include jq', u'inclusion': True, u'type': u'rpm', u'packages': [u'jq', u'oniguruma'], u'repositories': u'EPEL-7'}]}) => {"ansible_loop_var": "item", "changed": true, "entity": {}, "item": {"filters": [{"inclusion": true, "name": "Include jq", "packages": ["jq", "oniguruma"], "product": "Extra Packages For Enterprise Linux", "repositories": "EPEL-7", "type": "rpm"}], "name": "CV-RHEL7", "repositories": [{"name": "Red Hat Enterprise Linux 7 Server RPMs x86_64 7Server", "product": "Red Hat Enterprise Linux Server"}, {"name": "Red Hat Enterprise Linux 7 Server Kickstart x86_64 7.7", "product": "Red Hat Enterprise Linux Server"}, {"name": "EPEL-7", "product": "Extra Packages For Enterprise Linux"}]}}

TASK [sat6-activation-keys : ensure activation keys exist] ***********************************************************************************************************************************************************************************
fatal: [satellite.example.com]: FAILED! => {"msg": "'localhost' is undefined"}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
satellite.example.com       : ok=20   changed=13   unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```
```
# vars/sat-vars.yml


# this url will be used to access the satellite api
server_url: "https://{{ ansible_nodename }}"

# specify username and password of the initial admin user
username: admin
password: redhat123

# set to False if using self-signed certs on satellite
validate_certs: True

# set to True if you want to execute hammer commands on the ansible host
# rather than on the satellite
hammer_local: False

# set to False if you want to execute foreman-ansible-modules on the 
# satellite rather than the ansible host 
fam_local: True

---
activation_keys:
- name: AK-CI-RHEL7
  lifecycle_environment: CI
  content_view: CV-RHEL7
  release_version: 7Server
  subscriptions:
  - name: Red Hat Enterprise Linux
  - name: Extra Packages For Enterprise Linux

- name: AK-TEST-RHEL7
  lifecycle_environment: TEST
  content_view: CV-RHEL7
  release_version: 7Server
  subscriptions:
  - name: Red Hat Enterprise Linux
  - name: Extra Packages For Enterprise Linux

- name: AK-QA-RHEL7
  lifecycle_environment: QA
  content_view: CV-RHEL7
  release_version: 7Server
  subscriptions:
  - name: Red Hat Enterprise Linux
  - name: Extra Packages For Enterprise Linux

- name: AK-PROD-RHEL7
  lifecycle_environment: PROD
  content_view: CV-RHEL7
  release_version: 7Server
  subscriptions:
  - name: Red Hat Enterprise Linux
  - name: Extra Packages For Enterprise Linux
```
```
# ansible --version
ansible 2.8.6
  config file = /root/sat6-deployer/ansible.cfg
  configured module search path = [u'/root/sat6-deployer/foreman-ansible-modules/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```
